import type { ReactNode } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { Dovie } from '@/components/brand';
import { AppText, Button, Card } from '@/components/ui';
import { colors, spacing } from '@/design-system/tokens';

export type ReportStat = { label: string; value: string; detail?: string };

export function ReportHeader({ month, subtitle }: { month: string; subtitle?: string }) { return <View style={styles.stack}><AppText variant="headingLg">Báo cáo {month}</AppText>{subtitle ? <AppText color="secondary">{subtitle}</AppText> : null}</View>; }
export function ReportHeroCard({ summary, title = 'Tháng của bạn' }: { title?: string; summary: string }) { return <Card variant="soft"><View style={styles.hero}><View style={styles.stack}><AppText variant="headingMd">{title}</AppText><AppText color="body">{summary}</AppText></View><Dovie decorative pose="thinking" size={88} /></View></Card>; }
export function ReportStatCard({ detail, label, value }: ReportStat) { return <Card><View style={styles.stack}><AppText color="secondary" variant="label">{label}</AppText><AppText color="brand" variant="metric">{value}</AppText>{detail ? <AppText color="muted" variant="label">{detail}</AppText> : null}</View></Card>; }
export function ReportStatsGrid({ stats }: { stats: ReportStat[] }) { return <View style={styles.grid}>{stats.map(stat => <View key={stat.label} style={styles.half}><ReportStatCard {...stat} /></View>)}</View>; }
export function MoodTrendChart({ points, accessibilityLabel = 'Biểu đồ xu hướng tâm trạng' }: { points: number[]; accessibilityLabel?: string }) { const max = Math.max(...points, 1); return <View accessibilityLabel={accessibilityLabel} accessibilityRole="image" style={styles.chart}>{points.map((point, index) => <View key={`${index}-${point}`} style={[styles.bar, { height: `${Math.max(12, point / max * 100)}%` }]} />)}</View>; }
export function MoodChartLegend({ items }: { items: { color: string; label: string }[] }) { return <View style={styles.legend}>{items.map(item => <View key={item.label} style={styles.legendItem}><View style={[styles.dot, { backgroundColor: item.color }]} /><AppText color="secondary" variant="label">{item.label}</AppText></View>)}</View>; }
export function MoodTrendCard({ legend, points, title = 'Xu hướng cảm xúc' }: { title?: string; points: number[]; legend: { color: string; label: string }[] }) { return <Card><View style={styles.stack}><AppText variant="headingMd">{title}</AppText><MoodTrendChart points={points} /><MoodChartLegend items={legend} /></View></Card>; }
export function MonthlyInsightCard({ children, title = 'Điều Dearest nhận thấy' }: { title?: string; children: ReactNode }) { return <Card variant="soft"><View style={styles.stack}><AppText variant="headingMd">{title}</AppText><AppText color="body">{children}</AppText></View></Card>; }
export function NextMonthSuggestionCard({ description, onPress, title = 'Gợi ý cho tháng tới' }: { title?: string; description: string; onPress?: () => void }) { return <Card><View style={styles.stack}><AppText variant="headingMd">{title}</AppText><AppText color="secondary">{description}</AppText>{onPress ? <Button label="Xem gợi ý" size="sm" onPress={onPress} /> : null}</View></Card>; }
export function ReportActions({ onShare, onViewDetails }: { onShare?: () => void; onViewDetails?: () => void }) { return <View style={styles.actions}>{onViewDetails ? <Button label="Xem chi tiết" variant="outline" onPress={onViewDetails} /> : null}{onShare ? <Button label="Chia sẻ" variant="secondary" onPress={onShare} /> : null}</View>; }

const styles = StyleSheet.create({ actions: { gap: spacing.sm }, bar: { backgroundColor: colors.brand.primary, borderRadius: 99, flex: 1, minHeight: 8 }, chart: { alignItems: 'flex-end', flexDirection: 'row', gap: spacing.sm, height: 112 }, dot: { borderRadius: 99, height: 10, width: 10 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, half: { flexBasis: '46%', flexGrow: 1 }, hero: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm }, legend: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, legendItem: { alignItems: 'center', flexDirection: 'row', gap: spacing.xs }, stack: { flex: 1, gap: spacing.sm } });
