import { Pressable, StyleSheet, View } from 'react-native';
import { AppText, Button, Card, ConfirmDialog, SwitchRow } from '@/components/ui';
import { ChecklistGroup, type ChecklistItemModel, PermissionStatusBadge, SafeSummaryCard } from '@/components/future-shared';
import { colors, radius, spacing } from '@/design-system/tokens';

export type PartnerConnectionState = 'none' | 'invited' | 'connected' | 'paused' | 'revoked' | 'disconnected';
export type PartnerPermissionKey = 'cycle_phase' | 'expected_period' | 'general_support_hints' | 'mood_summary' | 'symptom_summary' | 'energy_summary';
export type PartnerPermissionSnapshot = Partial<Record<PartnerPermissionKey, boolean>>;
const connectionLabels: Record<PartnerConnectionState, string> = { none: 'Chưa kết nối', invited: 'Đã gửi lời mời', connected: 'Đã kết nối', paused: 'Đã tạm dừng', revoked: 'Đã thu hồi', disconnected: 'Đã ngắt kết nối' };

export function PartnerInviteCard({ connected = false, onInvite, partnerName }: { connected?: boolean; partnerName?: string; onInvite: () => void }) { return <Card variant="soft"><View style={styles.stack}><AppText variant="headingMd">{connected ? `Bạn đang kết nối với ${partnerName ?? 'partner'}` : 'Mời một người đồng hành'}</AppText><AppText color="secondary">Partner chỉ xem những điều bạn chủ động cho phép và bạn có thể thu hồi bất kỳ lúc nào.</AppText>{connected ? null : <Button label="Mời partner" onPress={onInvite} />}</View></Card>; }
export function PartnerInviteCode({ code, expiresAt, onCopy, onShare, state = 'active' }: { code?: string; expiresAt?: string; state?: 'active' | 'copied' | 'expired' | 'regenerating' | 'error'; onCopy?: () => void; onShare?: () => void }) { return <Card><View style={styles.stack}><AppText variant="headingMd">Mã mời</AppText><AppText color={state === 'active' || state === 'copied' ? 'brand' : 'muted'} variant="metric">{code ?? '— — — —'}</AppText><AppText color="secondary" variant="label">{state === 'expired' ? 'Mã mời đã hết hạn' : expiresAt ? `Hết hạn ${expiresAt}` : 'Mã không chứa dữ liệu sức khỏe riêng tư.'}</AppText><View style={styles.actions}>{onCopy ? <Button label={state === 'copied' ? 'Đã sao chép' : 'Sao chép'} size="sm" variant="outline" onPress={onCopy} /> : null}{onShare ? <Button label="Chia sẻ" size="sm" onPress={onShare} /> : null}</View></View></Card>; }
export function PartnerConnectionStatus({ state }: { state: PartnerConnectionState }) { return <PermissionStatusBadge state={state === 'connected' ? 'shared' : state === 'paused' ? 'paused' : state === 'invited' ? 'pending' : state === 'revoked' ? 'revoked' : 'not_shared'} />; }
export function PartnerAvatar({ imageUrl: _imageUrl, name = 'Partner', size = 48 }: { name?: string; imageUrl?: string; size?: number }) { return <View accessibilityLabel={name} accessibilityRole="image" style={[styles.avatar, { height: size, width: size, borderRadius: size / 2 }]}><AppText color="inverse" variant="label">{name.slice(0, 1).toUpperCase()}</AppText></View>; }
export function PartnerSummaryCard({ energySummary, expectedPeriodText, moodSummary, permissions, phase, supportHint }: { phase?: string; expectedPeriodText?: string; supportHint?: string; moodSummary?: string; energySummary?: string; permissions: PartnerPermissionSnapshot }) { const canShow = (key: PartnerPermissionKey) => Boolean(permissions[key]); const summary = canShow('general_support_hints') && supportHint ? supportHint : 'Bạn có thể hỏi xem hôm nay cô ấy cần được hỗ trợ điều gì.'; return <SafeSummaryCard sourceLabel="Chỉ từ dữ liệu được cho phép chia sẻ" summary={summary} title={phase && canShow('cycle_phase') ? phase : 'Hôm nay có thể cần sự quan tâm'} icon={<PartnerAvatar size={32} />}>{/* privacy-safe, raw data intentionally omitted */}</SafeSummaryCard>; }
export function CyclePhaseShareCard({ description, phase, state = 'available' }: { phase?: string; description?: string; state?: 'available' | 'hidden' | 'insufficient' }) { const text = state === 'hidden' ? 'Chủ tài khoản không chia sẻ thông tin này.' : state === 'insufficient' ? 'Chưa đủ dữ liệu để hiển thị.' : description; return <Card><View style={styles.stack}><AppText color="secondary" variant="label">Giai đoạn hiện tại</AppText><AppText variant="headingMd">{state === 'available' ? phase ?? 'Chưa rõ' : 'Riêng tư'}</AppText><AppText color="secondary">{text}</AppText></View></Card>; }
export function SupportHintCard({ generatedFrom = 'general', hints, title }: { title: string; hints: string[]; generatedFrom?: 'general' | 'shared_context' }) { return <Card variant="soft"><View style={styles.stack}><AppText variant="headingMd">{title}</AppText>{hints.map(hint => <AppText key={hint}>♡ {hint}</AppText>)}{generatedFrom === 'shared_context' ? <AppText color="muted" variant="label">Dựa trên dữ liệu cô ấy cho phép chia sẻ</AppText> : null}</View></Card>; }
export function SupportActionCard({ completed = false, description, onPress, title }: { title: string; description?: string; completed?: boolean; onPress: () => void }) { return <Pressable accessibilityLabel={title} accessibilityRole="button" accessibilityState={{ disabled: completed }} disabled={completed} style={[styles.task, completed && styles.done]} onPress={onPress}><View style={styles.copy}><AppText variant="label">{completed ? '✓ ' : ''}{title}</AppText>{description ? <AppText color="secondary" variant="label">{description}</AppText> : null}</View></Pressable>; }
export function SharedPlanCard({ items, title = 'Kế hoạch chung' }: { title?: string; items: ChecklistItemModel[] }) { return <ChecklistGroup description="Cùng nhau chuẩn bị từng việc nhỏ." items={items} title={title} />; }
export function PartnerTaskCard({ completed, dueAt, note, onToggle, title }: { title: string; note?: string; dueAt?: string; completed: boolean; onToggle: () => void }) { return <Pressable accessibilityLabel={title} accessibilityRole="checkbox" accessibilityState={{ checked: completed }} style={[styles.task, completed && styles.done]} onPress={onToggle}><View style={[styles.checkbox, completed && styles.checked]}><AppText color="inverse" variant="label">{completed ? '✓' : ''}</AppText></View><View style={styles.copy}><AppText variant="label">{title}</AppText>{note ? <AppText color="secondary" variant="label">{note}</AppText> : null}{dueAt ? <AppText color="muted" variant="label">{dueAt}</AppText> : null}</View></Pressable>; }
export function SharedChecklist({ items, onToggleItem, title = 'Việc chung' }: { title?: string; items: ChecklistItemModel[]; onToggleItem: (id: string, completed: boolean) => void }) { return <ChecklistGroup items={items} title={title} onToggleItem={onToggleItem} />; }
export function PartnerSharePermissionRow({ description, label, value, onValueChange }: { label: string; description: string; value: boolean; onValueChange: (value: boolean) => void }) { return <SwitchRow description={description} label={label} value={value} onValueChange={onValueChange} />; }
export function PartnerPrivacyNotice() { return <Card variant="soft"><View style={styles.stack}><AppText variant="label">Riêng tư theo mặc định</AppText><AppText color="secondary" variant="label">Nhật ký và cuộc trò chuyện với Dovie luôn riêng tư. Bạn có thể dừng hoặc thu hồi chia sẻ bất kỳ lúc nào.</AppText></View></Card>; }
export function PauseSharingBanner() { return <Card variant="warning"><AppText color="secondary">Chia sẻ hiện đang tạm dừng.</AppText></Card>; }
export function RevokePartnerModal({ loading = false, onCancel, onConfirm, visible }: { visible: boolean; loading?: boolean; onCancel: () => void; onConfirm: () => void }) { return <ConfirmDialog confirmLabel="Thu hồi quyền" destructive loading={loading} message="Partner sẽ không còn xem dữ liệu mới được chia sẻ. Bạn có thể kết nối lại sau." title="Thu hồi kết nối?" visible={visible} onCancel={onCancel} onConfirm={onConfirm} />; }

const styles = StyleSheet.create({ actions: { flexDirection: 'row', gap: spacing.sm }, avatar: { alignItems: 'center', backgroundColor: colors.brand.primary, justifyContent: 'center' }, checked: { backgroundColor: colors.brand.primary, borderColor: colors.brand.primary }, checkbox: { alignItems: 'center', borderColor: colors.border.default, borderRadius: radius.sm, borderWidth: 1, height: 24, justifyContent: 'center', width: 24 }, copy: { flex: 1, gap: spacing.xs }, done: { opacity: 0.7 }, stack: { gap: spacing.sm }, task: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md, minHeight: 44 } });
