import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { Pressable, StyleSheet, View } from 'react-native';
import { AppText, Badge, InlineActionLink } from '@/components/ui';
import { colors, spacing } from '@/design-system/tokens';

export function TodaySummaryCard({ energy, mood, onSuggestion }: { mood: string; energy: string; onSuggestion: () => void }) { return <Pressable accessibilityRole="button" accessibilityLabel="Xem gợi ý hôm nay" style={styles.flatRow} onPress={onSuggestion}><View style={styles.metrics}><Metric icon="emoticon-outline" label="Tâm trạng" value={mood} /><Metric icon="lightning-bolt-outline" label="Năng lượng" value={energy} /></View><InlineActionLink label="Xem lại check-in" /></Pressable>; }
export function UpcomingPredictionCard({ days, onCalendar }: { days: number; onCalendar: () => void }) { return <Pressable accessibilityRole="button" accessibilityLabel="Xem lịch chu kỳ" style={styles.flatRow} onPress={onCalendar}><View style={styles.stack}><AppText color="brand" variant="label">SẮP TỚI</AppText><AppText variant="headingMd">Khoảng {days} ngày nữa</AppText><AppText color="secondary">Kỳ kinh tiếp theo là ước tính dựa trên chu kỳ hiện tại.</AppText><Badge label="Ước tính" tone="predicted" /></View><InlineActionLink label="Xem lịch" /></Pressable>; }

export function HomeDiscoverCard({ onPress }: { onPress: () => void }) { return <Pressable accessibilityRole="link" accessibilityLabel="Đọc bài viết về chu kỳ" style={styles.flatRow} onPress={onPress}><View style={styles.stack}><AppText color="brand" variant="label">GỢI Ý CHO HÔM NAY</AppText><AppText variant="headingMd">Hiểu nhịp cơ thể của bạn</AppText><AppText color="secondary" variant="label">3 phút đọc</AppText></View><MaterialCommunityIcons color={colors.brand.primary} name="chevron-right" size={24} /></Pressable>; }

function Metric({ icon, label, value }: { icon: keyof typeof MaterialCommunityIcons.glyphMap; label: string; value: string }) { return <View style={styles.metric}><MaterialCommunityIcons color={colors.brand.primary} name={icon} size={20} /><View><AppText color="secondary" variant="label">{label}</AppText><AppText variant="label">{value}</AppText></View></View>; }
const styles = StyleSheet.create({ flatRow: { borderBottomColor: colors.border.soft, borderBottomWidth: StyleSheet.hairlineWidth, gap: spacing.md, paddingVertical: spacing.lg }, metric: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: spacing.sm }, metrics: { flexDirection: 'row', gap: spacing.sm }, stack: { gap: spacing.sm } });
