import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import * as React from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { Screen, ScreenHeader, SectionHeader, StickyActions } from '@/components/layout';
import { Dovie, DovieMicro } from '@/components/brand';
import { getCycleDay, todayKey, useCoreStore } from '@/features/core/use-core-store';
import { AppText, Button, Card, EmptyState, HealthSafetyNotice, IconButton, InlineActionLink } from '@/components/ui';
import { colors, spacing } from '@/design-system/tokens';
import { translate, useSelectedLanguage } from '@/lib/i18n';
import { AssistantMessageBubble, ChatActionButton, ChatActionPanel, ChatComposer, ChatHeader, ChatHero, QuickReplyList, TypingIndicator, UserMessageBubble } from '@/features/chat/components';
import { CheckInActions, CheckInSection, DailyNoteSection, EnergyPicker, FlowPicker, MoodPicker, SymptomPicker, type EnergyValue, type FlowValue, type MoodValue } from '@/features/check-in/components';
import { CalendarLegend, CalendarWeekHeader, CycleCalendar, CycleRegularitySelector, CycleRing, CycleStatsRow, CycleStat, MonthNavigator, MonthlyReportPreviewCard, SelectedDayCard } from '@/features/cycle/components';
import { HomeDiscoverCard, HomeDovieBanner, HomeGreeting, UpcomingPredictionCard } from '@/features/home/components';
import { usePreferencesStore } from '@/features/management/use-preferences-store';
import { JournalAIConsentNotice, JournalEditor, JournalEmptyState, JournalList, type JournalEntry } from '@/features/journal/components';
import { ArticleBody, ArticleDisclaimer, ArticleHeader, ArticleSection, FeaturedKnowledgeCard, KnowledgeArticleGrid, KnowledgeHeader, KnowledgeSearch, type KnowledgeArticle } from '@/features/knowledge/components';
import { NotificationSettingRow, ReminderTimePicker } from '@/features/notifications/components';
import { DataUsageSummary, DeleteDataFlow, PrivacySettingRow } from '@/features/privacy/components';
import { MoodTrendCard, NextMonthSuggestionCard, ReportActions, ReportHeader, ReportHeroCard, ReportStatsGrid } from '@/features/reports/components';
import { AcceptSuggestionButton, SelfCareSuggestionCard, SelfCareSuggestionGrid, SuggestionHeroCard, SuggestionReasonCard } from '@/features/suggestions/components';

const symptomOptions = [{ id: 'cramps', label: 'Đau bụng' }, { id: 'backache', label: 'Đau lưng' }, { id: 'tired', label: 'Mệt' }, { id: 'acne', label: 'Nổi mụn' }, { id: 'bloating', label: 'Đầy bụng' }, { id: 'sleepy', label: 'Buồn ngủ' }, { id: 'sweet', label: 'Thèm đồ ngọt' }];
const articles: KnowledgeArticle[] = [{ id: '1', category: 'Chu kỳ', title: 'Hiểu nhịp chu kỳ của bạn', excerpt: 'Một vài dấu hiệu thường gặp và cách ghi nhận dịu dàng.', readTime: '4 phút đọc' }, { id: '2', category: 'Chăm sóc', title: 'Một ngày mệt, mình có thể làm gì?', excerpt: 'Các gợi ý wellbeing nhỏ, dễ thử.', readTime: '3 phút đọc' }];
const initialEntries: JournalEntry[] = [{ id: '1', dateLabel: 'Hôm nay', preview: 'Mình muốn nghỉ ngơi sớm hơn một chút.', private: true }];
const homeMoodLabel = (value: MoodValue) => ({ happy: 'Vui', irritated: 'Cáu nhẹ', neutral: 'Bình thường', sad: 'Hơi buồn', tired: 'Mệt' } as const)[value];
const homeEnergyLabel = (value: EnergyValue) => ({ good: 'Tốt', low: 'Thấp', medium: 'Vừa' } as const)[value];

export function HomeScreen() {
  const router = useRouter(); const cycle = useCoreStore(state => state.cycle); const checkIns = useCoreStore(state => state.checkIns); const todayCheckIn = checkIns[todayKey()]; const lifeStage = usePreferencesStore(state => state.lifeStage); const { language } = useSelectedLanguage();
  const cycleDay = cycle ? getCycleDay(cycle) : null;
  const dateLabel = new Intl.DateTimeFormat(language === 'vi' ? 'vi-VN' : 'en-US', { day: 'numeric', month: 'long' }).format(new Date());
  const dovieState = todayCheckIn?.energy === 'low' ? 'rest' : todayCheckIn?.mood === 'sad' ? 'care' : todayCheckIn ? 'encourage' : lifeStage === 'ttc' ? 'encourage' : lifeStage === 'cycle' ? 'default' : 'care';
  const contextLabel = lifeStage === 'ttc' ? translate('today.stage_ttc') : lifeStage === 'pregnancy' ? translate('today.stage_pregnancy') : lifeStage === 'postpartum' ? translate('today.stage_postpartum') : lifeStage === 'motherhood' ? translate('today.stage_motherhood') : cycleDay ? translate('today.cycle_day', { count: cycleDay }) : translate('today.no_cycle_context');
  const contextMessage = todayCheckIn ? translate('today.completed_context') : translate('today.informational_context');
  return <Screen scroll><View style={styles.stack}><HomeGreeting eyebrow={dateLabel} greeting={translate('home.hello')} name={translate('home.name')} />
    <HomeDovieBanner message={contextMessage} summary={todayCheckIn ? { energy: homeEnergyLabel(todayCheckIn.energy), mood: homeMoodLabel(todayCheckIn.mood) } : undefined} title={todayCheckIn ? 'Hôm nay của bạn' : contextLabel} state={dovieState} />
    {!todayCheckIn ? <Button label={translate('today.checkin')} onPress={() => router.push(`/check-in/${todayKey()}`)} /> : <Pressable accessibilityRole="button" accessibilityLabel="Xem lại check-in" style={styles.inlineLink} onPress={() => router.push(`/check-in/${todayKey()}`)}><InlineActionLink label="Xem lại check-in" /></Pressable>}
    {!cycle ? <Pressable accessibilityRole="button" accessibilityLabel={translate('today.add_cycle')} style={styles.infoSection} onPress={() => router.push('/cycle/edit')}><AppText variant="label">SẮP TỚI</AppText><AppText color="secondary">{translate('today.cycle_needed_description')}</AppText><InlineActionLink label={translate('today.add_cycle')} /></Pressable> : null}
    {todayCheckIn && Object.keys(checkIns).length >= 3 ? <Pressable accessibilityRole="button" accessibilityLabel={translate('today.view_insights')} style={styles.infoSection} onPress={() => router.push('/insights')}><AppText variant="label">NHỊP CỦA BẠN</AppText><AppText color="secondary">{translate('today.insight_description')}</AppText><InlineActionLink label={translate('today.view_insights')} /></Pressable> : null}
    {cycle && cycleDay ? <UpcomingPredictionCard days={Math.max(cycle.cycleLength - cycleDay, 0)} onCalendar={() => router.push('/journey')} /> : null}
    <HomeDiscoverCard onPress={() => router.push('/article/cycle-basics')} />
  </View></Screen>;
}

export function CalendarScreen() {
  const router = useRouter(); const cycle = useCoreStore(state => state.cycle); const [selectedDay, setSelectedDay] = React.useState(2);
  return <Screen scroll><View style={styles.stack}>
    <ScreenHeader title="Chu kỳ" trailing={<IconButton accessibilityLabel="Ghi nhận hôm nay" icon={<AppText>+</AppText>} onPress={() => router.push(`/check-in/${todayKey()}`)} />} />
    {cycle ? <><MonthNavigator label="Tháng 9, 2026" onNext={() => {}} onPrevious={() => {}} /><CalendarWeekHeader /><CycleCalendar days={calendarDays(selectedDay)} onSelectDay={day => setSelectedDay(day.day)} /><CalendarLegend /><SelectedDayCard dateLabel={`${selectedDay} tháng 9`} description="Dữ liệu bạn ghi nhận và dữ liệu dự đoán được hiển thị khác nhau." title={selectedDay === 2 ? 'Hôm nay' : 'Ngày đã chọn'} /><Button label="Chỉnh sửa chu kỳ" size="sm" variant="outline" onPress={() => router.push('/cycle/edit')} /></> : <EmptyState actionLabel="Thiết lập chu kỳ" description="Khi có thông tin baseline, lịch sẽ hiển thị rõ dữ liệu bạn ghi nhận và phần dự đoán." icon={<DovieMicro decorative size={96} state="empty" />} onAction={() => router.push('/cycle/edit')} title="Chưa có dữ liệu chu kỳ" />}
  </View></Screen>;
}

export function CheckInScreen() {
  const router = useRouter(); const { date } = useLocalSearchParams<{ date?: string }>(); const checkInDate = typeof date === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(date) ? date : todayKey(); const saved = useCoreStore(state => state.checkIns[checkInDate]); const saveCheckIn = useCoreStore(state => state.saveCheckIn);
  const [mood, setMood] = React.useState<MoodValue>(saved?.mood ?? 'neutral'); const [symptoms, setSymptoms] = React.useState<string[]>(saved?.symptoms ?? []); const [flow, setFlow] = React.useState<FlowValue>(saved?.flow ?? 0); const [energy, setEnergy] = React.useState<EnergyValue>(saved?.energy ?? 'medium'); const [note, setNote] = React.useState(saved?.note ?? ''); const [savedState, setSavedState] = React.useState(false);
  const save = () => { saveCheckIn({ date: checkInDate, mood, symptoms, flow, energy, note: note.trim() || undefined }); setSavedState(true); };
  return <Screen scroll contentContainerStyle={styles.bottom}><View style={styles.stack}><ScreenHeader title="Check-in" onBack={() => router.back()} />{savedState ? <View style={styles.success}><Dovie decorative motion="celebrate" pose="celebrate" size={56} /><AppText align="center" variant="headingMd">✓ Đã lưu check-in</AppText><AppText align="center" color="secondary">Mình ghi lại rồi nhé ♡</AppText><Button label="Quay về hôm nay" onPress={() => router.back()} /></View> : <><View style={styles.checkInIntro}><AppText color="secondary" variant="label">{new Intl.DateTimeFormat('vi-VN', { day: 'numeric', month: 'long' }).format(new Date(`${checkInDate}T00:00:00`))}</AppText><AppText variant="headingLg">Hôm nay cậu thế nào?</AppText><AppText color="secondary">Chỉ mất khoảng một phút.</AppText></View><CheckInSection number={1} title="Tâm trạng"><MoodPicker value={mood} onChange={setMood} /></CheckInSection><CheckInSection number={2} title="Cơ thể" description="Chọn tất cả điều phù hợp"><SymptomPicker options={symptomOptions} value={symptoms} onChange={setSymptoms} /></CheckInSection><CheckInSection number={3} title="Lượng kinh" description="Không bắt buộc"><FlowPicker value={flow} onChange={setFlow} /></CheckInSection><CheckInSection number={4} title="Năng lượng"><EnergyPicker value={energy} onChange={setEnergy} /></CheckInSection><CheckInSection number={5} title="Ghi chú" description="Không bắt buộc"><DailyNoteSection value={note} onChangeText={setNote} /></CheckInSection><StickyActions><CheckInActions onSave={save} onSkip={() => router.back()} /></StickyActions></>}</View></Screen>;
}

export function JournalScreen() { const router = useRouter(); const [entries, setEntries] = React.useState(initialEntries); const [draft, setDraft] = React.useState(''); const add = () => { if (draft.trim()) { setEntries(value => [{ id: String(Date.now()), dateLabel: 'Hôm nay', preview: draft.trim(), private: true }, ...value]); setDraft(''); } }; return <Screen scroll><View style={styles.stack}><SectionHeader actionLabel="Viết mới" title="Nhật ký riêng tư" onAction={() => {}} /><JournalAIConsentNotice /><JournalEditor value={draft} onChangeText={setDraft} /><Button disabled={!draft.trim()} label="Lưu nhật ký" onPress={add} />{entries.length ? <JournalList entries={entries} onPressEntry={() => {}} /> : <JournalEmptyState onCreate={() => {}} />}</View></Screen>; }

export function ChatScreen() { const [text, setText] = React.useState(''); const [messages, setMessages] = React.useState<string[]>([]); const [typing, setTyping] = React.useState(false); const send = () => { if (text.trim()) { setMessages(value => [...value, text.trim()]); setText(''); setTyping(true); setTimeout(() => setTyping(false), 900); } }; return <Screen scroll contentContainerStyle={styles.bottom}><View style={styles.stack}><ChatHeader /><ChatHero message="Dovie ở đây để lắng nghe bạn." /><AssistantMessageBubble message="Hôm nay bạn thấy cơ thể và tâm trạng thế nào?" />{messages.map((message, index) => <UserMessageBubble key={`${index}-${message}`} message={message} />)}{typing ? <TypingIndicator /> : null}<QuickReplyList replies={['Hơi mệt', 'Muốn được lắng nghe', 'Hỏi về chu kỳ']} onSelect={reply => setText(reply)} /><ChatActionPanel><ChatActionButton label="Gợi ý chăm sóc" onPress={() => {}} /><ChatActionButton label="Ghi journal" onPress={() => {}} /></ChatActionPanel><View style={styles.safety}><DovieMicro decorative size={36} state="gentleAlert" /><HealthSafetyNotice message="Nếu triệu chứng nặng, kéo dài hoặc làm bạn lo lắng, hãy liên hệ cơ sở y tế phù hợp." title="Lưu ý sức khỏe" /></View><ChatComposer value={text} onChangeText={setText} onSend={send} /></View></Screen>; }

export function SuggestionsScreen() { const router = useRouter(); const checkIn = useCoreStore(state => state.checkIns[todayKey()]); const personalized = Boolean(checkIn); const lowEnergy = checkIn?.energy === 'low' || checkIn?.mood === 'tired'; const doviePose = lowEnergy ? 'rest' : personalized ? 'care' : 'encourage'; return <Screen scroll><View style={styles.stack}><ScreenHeader title="Gợi ý hôm nay" onBack={() => router.back()} /><Dovie decorative pose={doviePose} size={140} /><SuggestionHeroCard basis={personalized ? 'Check-in hôm nay do bạn ghi nhận' : 'Gợi ý chung'} description={lowEnergy ? 'Hãy ưu tiên một nhịp nghỉ ngắn cho cơ thể.' : 'Chọn một việc nhỏ, nhẹ nhàng và phù hợp với bạn hôm nay.'} title={lowEnergy ? 'Dành cho ngày hơi mệt' : 'Một gợi ý dịu dàng'} /><SelfCareSuggestionGrid><SelfCareSuggestionCard actionLabel="Thử ngay" description={lowEnergy ? 'Ngồi thả lỏng, uống nước và cho mình vài phút nghỉ.' : 'Hít thở chậm và viết một dòng về điều bạn cần hôm nay.'} title="Một việc nhỏ" onPress={() => {}} /></SelfCareSuggestionGrid><SuggestionReasonCard reason={personalized ? 'Gợi ý này dựa trên check-in hôm nay của bạn.' : 'Bạn chưa ghi check-in hôm nay, nên đây là gợi ý chung.'} title="Vì sao có gợi ý này?" /><AcceptSuggestionButton onPress={() => router.back()} /></View></Screen>; }

export function ReportScreen() { const router = useRouter(); const checkIns = useCoreStore(state => Object.values(state.checkIns)); const cycle = useCoreStore(state => state.cycle); const moodCounts = checkIns.reduce<Record<string, number>>((counts, item) => ({ ...counts, [item.mood]: (counts[item.mood] ?? 0) + 1 }), {}); const commonMood = Object.entries(moodCounts).sort((a, b) => b[1] - a[1])[0]?.[0] ?? '—'; const moodLabel = ({ happy: 'Vui', neutral: 'Bình thường', sad: 'Hơi buồn', irritated: 'Cáu nhẹ', tired: 'Mệt' } as Record<string, string>)[commonMood] ?? commonMood; return <Screen scroll><View style={styles.stack}><ScreenHeader title="Báo cáo tháng" onBack={() => router.back()} /><ReportHeader month="tháng này" />{checkIns.length < 2 ? <EmptyState description="Hãy ghi nhận thêm vài ngày để Dearest có thể tạo báo cáo dựa trên dữ liệu của bạn." icon={<DovieMicro decorative size={96} state="empty" />} title="Chưa đủ dữ liệu" /> : <><ReportHeroCard summary="Báo cáo này chỉ dùng những check-in bạn đã tự ghi nhận." /><ReportStatsGrid stats={[{ label: 'Chu kỳ', value: cycle ? `${cycle.cycleLength} ngày` : 'Chưa đủ' }, { label: 'Kỳ kinh', value: cycle ? `${cycle.periodLength} ngày` : 'Chưa đủ' }, { label: 'Mood thường gặp', value: moodLabel }, { label: 'Check-in', value: `${checkIns.length} ngày` }]} /><MoodTrendCard legend={[{ color: colors.mood.happy.accent, label: 'Tích cực' }, { color: colors.mood.sad.accent, label: 'Thấp hơn' }]} points={checkIns.map(item => item.mood === 'happy' ? 4 : item.mood === 'neutral' ? 3 : 2)} /><NextMonthSuggestionCard description="Đặt một lời nhắc nhẹ nhàng cho những ngày bạn thường thấy mệt." /></>}<ReportActions onViewDetails={() => router.push('/calendar')} /></View></Screen>; }

export function KnowledgeScreen() { const router = useRouter(); const [query, setQuery] = React.useState(''); const visible = articles.filter(item => item.title.toLowerCase().includes(query.toLowerCase())); return <Screen scroll><View style={styles.stack}><ScreenHeader title="Kiến thức" onBack={() => router.back()} /><KnowledgeHeader subtitle="Thông tin để hiểu mình hơn, không thay thế tư vấn y tế." /><KnowledgeSearch value={query} onChangeText={setQuery} /><FeaturedKnowledgeCard article={articles[0]} onPress={() => router.push('/knowledge/cycle-basics')} />{visible.length ? <KnowledgeArticleGrid articles={visible} onPressArticle={article => router.push(`/knowledge/${article.id}`)} /> : <EmptyState description="Thử từ khóa khác nhé." title="Không tìm thấy bài viết" />}</View></Screen>; }

export function ArticleDetailScreen() { const router = useRouter(); return <Screen scroll><View style={styles.stack}><ScreenHeader title="Bài viết" onBack={() => router.back()} /><ArticleHeader article={articles[0]} /><ArticleSection title="Nhịp của bạn"><ArticleBody>Chu kỳ mỗi người có thể khác nhau. Ghi nhận đều đặn giúp bạn nhận ra điều gì phù hợp với cơ thể mình.</ArticleBody></ArticleSection><ArticleDisclaimer /></View></Screen>; }

export function SettingsScreen() { const router = useRouter(); return <Screen scroll><View style={styles.stack}><ScreenHeader title="Cài đặt" /><SectionHeader title="Hồ sơ & sở thích" /><Button label="Chỉnh thông tin chu kỳ" variant="outline" onPress={() => router.push('/cycle/edit')} /><SectionHeader title="Quyền riêng tư" /><Button label="Dữ liệu & cá nhân hóa" variant="outline" onPress={() => router.push('/settings/privacy')} /><SectionHeader title="Nhắc nhở" /><Button label="Quản lý thông báo" variant="outline" onPress={() => router.push('/settings/notifications')} /></View></Screen>; }

export function NotificationSettingsScreen() { const router = useRouter(); const [checkIn, setCheckIn] = React.useState(true); const [period, setPeriod] = React.useState(false); return <Screen scroll><View style={styles.stack}><ScreenHeader title="Nhắc nhở" onBack={() => router.back()} /><NotificationSettingRow description="Nội dung nhắc kín đáo." label="Check-in hằng ngày" value={checkIn} onValueChange={setCheckIn} /><ReminderTimePicker value="20:00" onPress={() => {}} /><NotificationSettingRow description="Chỉ dựa trên dữ liệu đủ điều kiện dự đoán." label="Kỳ kinh ước tính" value={period} onValueChange={setPeriod} /></View></Screen>; }

export function PrivacyScreen() { const router = useRouter(); const [ai, setAi] = React.useState(true); const [journal, setJournal] = React.useState(false); return <Screen scroll><View style={styles.stack}><ScreenHeader title="Quyền riêng tư" onBack={() => router.back()} /><Dovie decorative pose="privacy" size={128} /><PrivacySettingRow description="Dùng cycle và check-in được phép cho gợi ý." label="Cá nhân hóa với AI" value={ai} onValueChange={setAi} /><PrivacySettingRow description="Nhật ký luôn riêng tư trừ khi bạn bật quyền này." label="Dùng nhật ký cho AI" value={journal} onValueChange={setJournal} /><DataUsageSummary items={['Bạn kiểm soát dữ liệu được dùng.', 'Thu hồi quyền có hiệu lực cho context sau đó.']} /><DeleteDataFlow onDelete={() => {}} /></View></Screen>; }

export function CycleEditScreen() { const router = useRouter(); const cycle = useCoreStore(state => state.cycle); const setCycle = useCoreStore(state => state.setCycle); const [regularity, setRegularity] = React.useState<'regular' | 'irregular'>(cycle?.regularity === 'irregular' ? 'irregular' : 'regular'); const day = cycle ? getCycleDay(cycle) : null; const save = () => { if (cycle) setCycle({ ...cycle, regularity }); router.back(); }; return <Screen scroll><View style={styles.stack}><ScreenHeader title="Chỉnh chu kỳ" onBack={() => router.back()} />{cycle && day ? <><CycleRing currentDay={day} totalDays={cycle.cycleLength} /><CycleStatsRow><CycleStat label="Độ dài" value={`${cycle.cycleLength} ngày`} /><CycleStat label="Kỳ kinh" value={`${cycle.periodLength} ngày`} /></CycleStatsRow><CycleRegularitySelector value={regularity} onChange={setRegularity} /><Button label="Lưu thay đổi" onPress={save} /></> : <EmptyState description="Thiết lập cycle baseline từ onboarding để Dearest có thể hiển thị và chỉnh sửa dữ liệu chu kỳ." icon={<DovieMicro decorative size={96} state="empty" />} title="Chưa có dữ liệu chu kỳ" />}</View></Screen>; }

function calendarDays(selectedDay: number) { return Array.from({ length: 42 }, (_, index) => { const day = index + 1; const current = day <= 30; const state = [4, 5, 6, 7].includes(day) ? 'actual' : [17, 18, 19, 20].includes(day) ? 'fertile' : [26, 27, 28].includes(day) ? 'predicted' : 'normal'; return { accessibilityLabel: `${day} tháng 9`, dateKey: `2026-09-${String(day).padStart(2, '0')}`, day, isCurrentMonth: current, isSelected: current && day === selectedDay, isToday: current && day === 2, key: String(index), state } as const; }); }
const styles = StyleSheet.create({ bottom: { paddingBottom: spacing.xxxl }, checkInIntro: { gap: spacing.sm }, infoSection: { gap: spacing.sm, paddingVertical: spacing.lg }, inlineLink: { alignSelf: 'flex-start' }, safety: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm }, stack: { gap: spacing.lg }, success: { alignItems: 'center', gap: spacing.lg } });
