import { Pressable, StyleSheet, View } from 'react-native';
import { AppText, Button, Card, SwitchRow } from '@/components/ui';
import { colors, spacing } from '@/design-system/tokens';

export function PrivacySettingRow({ description, label, value, onValueChange }: { label: string; description: string; value: boolean; onValueChange: (value: boolean) => void }) { return <SwitchRow description={description} label={label} value={value} onValueChange={onValueChange} />; }
export const ConsentSetting = PrivacySettingRow;
export function DataUsageSummary({ items }: { items: string[] }) { return <Card variant="soft"><View style={styles.stack}><AppText variant="headingMd">Dữ liệu của bạn</AppText>{items.map(item => <View key={item} style={styles.row}><View style={styles.dot} /><AppText color="secondary">{item}</AppText></View>)}</View></Card>; }
export function PartnerSharePermissionRow({ onPress, status = 'Chưa kết nối' }: { status?: string; onPress: () => void }) { return <Pressable accessibilityLabel="Chia sẻ với người đồng hành" accessibilityRole="button" style={({ pressed }) => [styles.partner, pressed && styles.pressed]} onPress={onPress}><View style={styles.stack}><AppText variant="label">Chia sẻ với người đồng hành</AppText><AppText color="secondary" variant="label">{status}</AppText></View><AppText color="brand" variant="label">Quản lý</AppText></Pressable>; }
export function DeleteDataFlow({ loading = false, onDelete }: { loading?: boolean; onDelete: () => void }) { return <Card variant="warning"><View style={styles.stack}><AppText color="danger" variant="headingMd">Xóa dữ liệu</AppText><AppText color="secondary">Thao tác này sẽ xóa dữ liệu khỏi trải nghiệm cá nhân hóa đang hoạt động.</AppText><Button label="Xóa dữ liệu của tôi" loading={loading} variant="destructive" onPress={onDelete} /></View></Card>; }
const styles = StyleSheet.create({ dot: { backgroundColor: colors.brand.primary, borderRadius: 99, height: 6, width: 6 }, partner: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: 56 }, pressed: { opacity: 0.75 }, row: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm }, stack: { gap: spacing.sm } });
