import { Pressable, StyleSheet, View } from 'react-native';
import { AppText, Card, Chip, EmptyState } from '@/components/ui';
import type { WidgetPrivacyMode, WidgetSnapshot, WidgetType } from '@/widgets/contracts/widget-snapshot';
import { colors, radius, spacing } from '@/design-system/tokens';

export function WidgetSurface({ children, size = 'small' }: { children: React.ReactNode; size?: 'small' | 'medium' | 'lockscreen' }) { return <View style={[styles.surface, styles[size]]}>{children}</View>; }
export function WidgetHeader({ title }: { title: string }) { return <AppText variant="label">{title}</AppText>; }
export function WidgetMascot({ compact = false }: { compact?: boolean }) { return <View accessibilityLabel="Dovie" accessibilityRole="image" style={[styles.mascot, compact && styles.mascotCompact]}><AppText color="inverse" variant="label">D</AppText></View>; }
export function WidgetMetric({ label, value }: { value: string; label?: string }) { return <View><AppText color="brand" variant="metric">{value}</AppText>{label ? <AppText color="secondary" variant="label">{label}</AppText> : null}</View>; }
export function WidgetMessage({ children }: { children: React.ReactNode }) { return <AppText color="secondary" variant="label">{children}</AppText>; }
export function WidgetQuickAction({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable accessibilityLabel={label} accessibilityRole="button" style={styles.action} onPress={onPress}><AppText color="brand" variant="label">{label}</AppText></Pressable>; }
export function WidgetMoodAction({ label, onPress }: { label: string; onPress: () => void }) { return <WidgetQuickAction label={label} onPress={onPress} />; }
export function WidgetPrivacyIndicator({ mode }: { mode: WidgetPrivacyMode }) { return <AppText color="muted" variant="label">{mode === 'discreet' ? 'Riêng tư' : 'Hiển thị bình thường'}</AppText>; }
export function WidgetStaleState() { return <AppText color="muted" variant="label">Cập nhật lần cuối trước đó</AppText>; }
export function WidgetEmptyState() { return <EmptyState description="Mở Dearest để bắt đầu cá nhân hóa widget." title="Chưa có dữ liệu" />; }
export function WidgetPreviewCard({ size, snapshot, widgetType }: { widgetType: WidgetType; size: 'small' | 'medium' | 'lockscreen'; snapshot: WidgetSnapshot }) { const discreet = snapshot.privacyMode === 'discreet'; return <Card><View style={styles.preview}><AppText color="muted" variant="label">Xem trước · {widgetType}</AppText><WidgetSurface size={size}><View style={styles.top}><WidgetHeader title="Dearest" /><WidgetMascot compact /></View>{snapshot.metric && !discreet ? <WidgetMetric value={snapshot.metric} /> : null}<WidgetMessage>{discreet ? 'Một lời nhắn từ Dearest' : snapshot.message ?? 'Mở Dearest để xem hôm nay của bạn.'}</WidgetMessage><WidgetPrivacyIndicator mode={snapshot.privacyMode} />{snapshot.isStale ? <WidgetStaleState /> : null}</WidgetSurface></View></Card>; }
export function WidgetGallery({ children }: { children: React.ReactNode }) { return <View style={styles.gallery}>{children}</View>; }
export function WidgetSizeSelector({ value, onChange }: { value: 'small' | 'medium' | 'lockscreen'; onChange: (value: 'small' | 'medium' | 'lockscreen') => void }) { return <View style={styles.choices}>{(['small', 'medium', 'lockscreen'] as const).map(item => <Chip key={item} label={item === 'lockscreen' ? 'Lock Screen' : item === 'small' ? 'Small' : 'Medium'} selected={value === item} onPress={() => onChange(item)} />)}</View>; }
export function WidgetPrivacyModeSelector({ value, onChange }: { value: WidgetPrivacyMode; onChange: (value: WidgetPrivacyMode) => void }) { return <View style={styles.choices}><Chip label="Bình thường" selected={value === 'normal'} onPress={() => onChange('normal')} /><Chip label="Kín đáo" selected={value === 'discreet'} onPress={() => onChange('discreet')} /></View>; }
export function WidgetContentSelector({ value, onChange }: { value: WidgetType; onChange: (value: WidgetType) => void }) { return <View style={styles.choices}>{([{ key: 'cycle_countdown', label: 'Chu kỳ' }, { key: 'daily', label: 'Dovie' }, { key: 'mood_check_in', label: 'Check-in' }, { key: 'pregnancy_week', label: 'Thai kỳ' }] as const).map(item => <Chip key={item.key} label={item.label} selected={value === item.key} onPress={() => onChange(item.key)} />)}</View>; }
export function WidgetMascotSelector({ compact, onChange }: { compact: boolean; onChange: (compact: boolean) => void }) { return <View style={styles.choices}><Chip label="Dovie" selected={!compact} onPress={() => onChange(false)} /><Chip label="Gọn" selected={compact} onPress={() => onChange(true)} /></View>; }

const styles = StyleSheet.create({ action: { borderColor: colors.brand.primary, borderRadius: radius.pill, borderWidth: 1, minHeight: 44, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, gallery: { gap: spacing.md }, lockscreen: { minHeight: 88 }, mascot: { alignItems: 'center', backgroundColor: colors.brand.primary, borderRadius: 18, height: 36, justifyContent: 'center', width: 36 }, mascotCompact: { borderRadius: 12, height: 24, width: 24 }, medium: { minHeight: 184 }, preview: { gap: spacing.sm }, small: { minHeight: 144 }, surface: { backgroundColor: colors.surface.soft, borderColor: colors.border.default, borderRadius: radius.lg, borderWidth: 1, gap: spacing.sm, justifyContent: 'space-between', padding: spacing.lg }, top: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' } });
