import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { StyleSheet, View } from 'react-native';
import { AppText, Badge, Card, Chip, HealthSafetyNotice } from '@/components/ui';
import { ContextSourceBadge, ModeHeroCard, ProgressSummaryCard, TimelineCard, type TimelineItem } from '@/components/future-shared';
import { colors, spacing } from '@/design-system/tokens';

export function TrimesterBadge({ trimester }: { trimester: 1 | 2 | 3 }) { return <Badge label={`Tam cá nguyệt ${trimester}`} tone="predicted" />; }
export function PregnancyWeekCard({ week, trimester }: { week?: number; trimester?: 1 | 2 | 3 }) { return <Card variant="soft"><View style={styles.stack}><AppText color="brand" variant="label">Hành trình mang thai</AppText><AppText variant="headingLg">{week ? `Tuần ${week}` : 'Chưa xác định tuần'}</AppText>{trimester ? <TrimesterBadge trimester={trimester} /> : null}<ContextSourceBadge source="system_calculated" /></View></Card>; }
export function PregnancyProgressBar({ week }: { week: number }) { return <ProgressSummaryCard current={week} label="Tiến trình thai kỳ" progress={week / 40} secondaryLabel="Mốc tham khảo 40 tuần" total={40} />; }
export function DueDateCard({ dateLabel }: { dateLabel?: string }) { return <Card><View style={styles.stack}><AppText variant="headingMd">Ngày dự sinh</AppText><AppText color="brand" variant="metric">{dateLabel ?? 'Chưa ước tính được'}</AppText><AppText color="secondary" variant="label">Đây là ước tính tham khảo, không phải ngày sinh chắc chắn.</AppText></View></Card>; }
export function MaternalWellbeingCard({ message, onPress }: { message: string; onPress?: () => void }) { return <ModeHeroCard actionLabel={onPress ? 'Check-in' : undefined} description={message} eyebrow="Wellbeing của mẹ" title="Hôm nay mẹ thấy thế nào?" onAction={onPress} />; }
export function MaternalCheckIn({ children }: { children: React.ReactNode }) { return <Card><View style={styles.stack}><AppText variant="headingMd">Check-in của mẹ</AppText><AppText color="secondary" variant="label">Ghi nhận cảm nhận của bạn, không phải đánh giá y khoa.</AppText>{children}</View></Card>; }
export function PregnancySymptomChip({ label, selected, onPress }: { label: string; selected?: boolean; onPress: () => void }) { return <Chip label={label} selected={selected} onPress={onPress} />; }
export function AppointmentCard({ dateLabel, provider, title }: { title: string; dateLabel?: string; provider?: string }) { return <Card><View style={styles.stack}><AppText variant="headingMd">{title}</AppText>{dateLabel ? <AppText color="brand" variant="label">{dateLabel}</AppText> : null}{provider ? <AppText color="secondary">{provider}</AppText> : null}</View></Card>; }
export function AppointmentTimeline({ items }: { items: TimelineItem[] }) { return <TimelineCard items={items} title="Lịch hẹn" />; }
export function PregnancySafetyCard({ message, title = 'Khi nào nên tìm hỗ trợ' }: { title?: string; message: string }) { return <HealthSafetyNotice message={message} title={title} />; }
export function BabyDevelopmentCard({ description, week }: { week?: number; description: string }) { return <Card variant="soft"><View style={styles.stack}><AppText variant="headingMd">Sự phát triển của bé{week ? ` · tuần ${week}` : ''}</AppText><AppText color="secondary">{description}</AppText><AppText color="muted" variant="label">Nội dung tham khảo đã được biên tập.</AppText></View></Card>; }
export function BabySizeIllustration({ accessibilityLabel = 'Minh họa kích thước em bé', caption }: { caption?: string; accessibilityLabel?: string }) { return <View accessibilityLabel={accessibilityLabel} accessibilityRole="image" style={styles.illustration}><MaterialCommunityIcons color={colors.brand.primary} name="heart-outline" size={36} />{caption ? <AppText color="secondary" variant="label">{caption}</AppText> : null}</View>; }
export function DoctorQuestionCard({ answered = false, question, onPress }: { question: string; answered?: boolean; onPress?: () => void }) { return <Card><View style={styles.stack}><AppText variant="label">{question}</AppText><AppText color={answered ? 'brand' : 'muted'} variant="label">{answered ? 'Đã trao đổi' : 'Để hỏi trong lần hẹn tới'}</AppText>{onPress ? <Chip label="Xem chi tiết" onPress={onPress} /> : null}</View></Card>; }
export function DoctorQuestionList({ questions }: { questions: { id: string; question: string; answered?: boolean }[] }) { return <View style={styles.stack}>{questions.map(item => <DoctorQuestionCard key={item.id} answered={item.answered} question={item.question} />)}</View>; }
export function DoviePregnancyCard({ message, onPress }: { message: string; onPress?: () => void }) { return <ModeHeroCard actionLabel={onPress ? 'Trò chuyện' : undefined} description={message} eyebrow="Dovie" title="Mình ở đây cùng bạn" onAction={onPress} />; }
export function PartnerPregnancyHintCard({ hint }: { hint: string }) { return <Card variant="soft"><View style={styles.stack}><AppText variant="headingMd">Một cách để hỗ trợ</AppText><AppText color="secondary">{hint}</AppText><AppText color="muted" variant="label">Chỉ dựa trên dữ liệu được cho phép chia sẻ.</AppText></View></Card>; }
const styles = StyleSheet.create({ illustration: { alignItems: 'center', backgroundColor: '#F9E1E7', borderRadius: 20, gap: spacing.sm, minHeight: 112, justifyContent: 'center', padding: spacing.lg }, stack: { gap: spacing.sm } });
